version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8081"  # Expose port 8081 from the container to port 8081 on the host
    environment:
      DATABASE_SECRET_KEY: ${DATABASE_SECRET_KEY}
      AWS_ACCESS_KEY: ${ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    mem_limit: 500m      # Limit the memory usage to 500 MB
    cpus: 1.0            # Limit the container to 1 CPU core

